# sdi2000014 - Theodora Archontaki #
CC = g++
modules = ask2_ESOR.cpp Process_data.cpp  
args = -o

ESOR: ask2_ESOR.cpp Process_data.cpp main.cpp 
	$(CC) main.cpp $(modules) $(args) esor

clean: 
	rm esor