# sdi2000014 - Theodora Archontaki #
CC = g++
modules = ask1_LL_a.cpp ask1_LL_b.cpp Process_data.cpp error.cpp
args = -o

LL: ask1_LL_a.cpp ask1_LL_b.cpp Process_data.cpp error.cpp  main.cpp 
	$(CC) main.cpp $(modules) $(args) ll

clean: 
	rm ll