# sdi2000014 - Theodora Archontaki #
CC = g++
modules = ask1_LU_a.cpp ask1_LU_b.cpp Process_data.cpp error.cpp 
args = -o

LU: ask1_LU_a.cpp ask1_LU_b.cpp Process_data.cpp error.cpp main.cpp 
	$(CC) main.cpp $(modules) $(args) lu

clean: 
	rm lu